# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_findmultPCs_deflation <- function(Sigma, r, ks_input, numIters = 200L, verbose = TRUE, violation_tolerance = 1e-4) {
    .Call('_sPCAmPC_cpp_findmultPCs_deflation', PACKAGE = 'sPCAmPC', Sigma, r, ks_input, numIters, verbose, violation_tolerance)
}

