# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

iterativeDeflationHeuristic <- function(Sigma, r, ks, maxIter = 200L, verbose = TRUE, violationTolerance = 1e-4, stallingTolerance = 1e-8, maxIterTPW = 200L, timeLimitTPW = 20L) {
    .Call('_msPCA_iterativeDeflationHeuristic', PACKAGE = 'msPCA', Sigma, r, ks, maxIter, verbose, violationTolerance, stallingTolerance, maxIterTPW, timeLimitTPW)
}

truncatedPowerMethod <- function(Sigma, k, maxIter = 200L, verbose = TRUE, timeLimit = 10L) {
    .Call('_msPCA_truncatedPowerMethod', PACKAGE = 'msPCA', Sigma, k, maxIter, verbose, timeLimit)
}

