# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

iterativeDeflationHeuristic <- function(Sigma, r, ks, feasibilityConstraintType = 0L, verbose = TRUE, maxIter = 200L, feasibilityTolerance = 1e-4, stallingTolerance = 1e-8, timeLimitTPM = 20L, maxRestartTPM = 20L, minRestartTPM = 10L) {
    .Call('_msPCA_iterativeDeflationHeuristic', PACKAGE = 'msPCA', Sigma, r, ks, feasibilityConstraintType, verbose, maxIter, feasibilityTolerance, stallingTolerance, timeLimitTPM, maxRestartTPM, minRestartTPM)
}

truncatedPowerMethod <- function(Sigma, k, maxIter = 200L, verbose = TRUE, timeLimit = 10L) {
    .Call('_msPCA_truncatedPowerMethod', PACKAGE = 'msPCA', Sigma, k, maxIter, verbose, timeLimit)
}

